In [1]:
import numpy as np
from wdmwavelet.wdmwavelet import _rwdm, PI, SQRT2, _gen_rolloff

In [2]:
nf = 6
nt = 5
n = nf * nt
steepness = 2

phi_tilde0 = [1, 1, .97, .243] + [0,] * 12
phi_tilde0 = np.array(phi_tilde0) * 2
phi_tilde1 = [0, 0, .243, .97, 1, 1, 1, .97, .243] + [0,] * 7
phi_tilde1 = np.array(phi_tilde1)
phi_tilde2 = [0,] * 7 + [.243, .97, 1, 1, 1, .97, .243, 0, 0]
phi_tilde2 = np.array(phi_tilde2)
phi_tilde3 = [0,]*12 + [ .243, .97, 1, 1]
phi_tilde3 = np.array(phi_tilde3) * 2
phi_tilde = np.vstack((phi_tilde0, phi_tilde1,
                       phi_tilde2, phi_tilde3)) / nt**.5 

x = np.random.randn(n)
x_tilde = np.fft.rfft(x, norm="ortho")
w = _rwdm(x, nt, nf, 2., steepness)

In [13]:
x_tilde_my = np.zeros(16, dtype=complex)
for k in range(16):
    for m in range(4):
        for n in range(10):

            if m == 0 or m == 3:
                A = 1
            else: A = SQRT2

            if (m + n) % 2 == 0:
                A_mn = A
            else: A_mn = -1j * A

            awe = A_mn * w[m][n] * np.exp(-1j*PI * n * k / nt)

            x_tilde_my[k] += phi_tilde[m][k] * awe

x_tilde_my /= 2.

In [12]:
x_tilde

array([-0.17070891+0.j        , -1.08594997-0.58587212j,
        0.20092351+0.06503317j,  0.87133948+0.76967387j,
       -0.1683806 -0.27544799j, -0.25860232-0.19380788j,
       -0.28186862+0.2045623j , -0.17774353-0.25871915j,
       -0.04178138+0.38564759j,  0.17568963+0.35197012j,
       -1.63197909-1.42736204j, -1.23238644+1.09425442j,
        0.70433664+0.02306847j,  0.29337031+0.48838325j,
        0.93167233-0.16812531j, -1.21041423+0.j        ])

In [14]:
np.abs(x_tilde_my-x_tilde)

array([5.55111512e-17, 5.97873396e-16, 3.42382176e-05, 2.72032851e-05,
       1.57009246e-16, 4.51828036e-16, 4.55225287e-16, 5.06665557e-06,
       1.77582774e-05, 8.21958773e-16, 1.73422380e-15, 2.58946282e-15,
       2.86994019e-05, 1.73512989e-05, 2.53230653e-15, 4.02294799e-15])

In [19]:
w[-1]

array([-7.64325849e-17,  2.94117431e+00,  1.11548335e-15, -8.07291225e-01,
       -1.32884839e-15,  5.56159275e-01,  9.37740681e-16, -1.13865039e+00,
       -2.85345734e-16,  4.57233238e+00])